/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "rgb(var(--c-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--c-primary-ctr) / <alpha-value>)",
        "on-primary": "rgb(var(--c-on-primary) / <alpha-value>)",
        "on-primary-container": "rgb(var(--c-on-primary-ctr) / <alpha-value>)",
        "secondary": "rgb(var(--c-secondary) / <alpha-value>)",
        "secondary-container": "rgb(var(--c-secondary-ctr) / <alpha-value>)",
        "on-secondary": "rgb(var(--c-on-secondary) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--c-on-secondary-ctr) / <alpha-value>)",
        "tertiary": "rgb(var(--c-tertiary) / <alpha-value>)",
        "tertiary-container": "rgb(var(--c-tertiary-ctr) / <alpha-value>)",
        "on-tertiary": "rgb(var(--c-on-tertiary) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--c-on-tertiary-ctr) / <alpha-value>)",
        "surface": "rgb(var(--c-surface) / <alpha-value>)",
        "surface-dim": "rgb(var(--c-surface-dim) / <alpha-value>)",
        "surface-bright": "rgb(var(--c-surface-brt) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--c-srf-lo) / <alpha-value>)",
        "surface-container-low": "rgb(var(--c-srf-low) / <alpha-value>)",
        "surface-container": "rgb(var(--c-srf-ctr) / <alpha-value>)",
        "surface-container-high": "rgb(var(--c-srf-hi) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--c-srf-hst) / <alpha-value>)",
        "surface-variant": "rgb(var(--c-surface-var) / <alpha-value>)",
        "on-surface": "rgb(var(--c-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--c-on-surface-var) / <alpha-value>)",
        "on-background": "rgb(var(--c-on-bg) / <alpha-value>)",
        "background": "rgb(var(--c-bg) / <alpha-value>)",
        "outline": "rgb(var(--c-outline) / <alpha-value>)",
        "outline-variant": "rgb(var(--c-outline-var) / <alpha-value>)",
        "primary-fixed": "rgb(var(--c-primary-fx) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--c-primary-fx-d) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--c-secondary-fx) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--c-secondary-fx-d) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--c-tertiary-fx) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--c-tertiary-fx-d) / <alpha-value>)",
        "surface-tint": "rgb(var(--c-surface-tint) / <alpha-value>)",
        "inverse-surface": "rgb(var(--c-inv-surface) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--c-inv-on-surface) / <alpha-value>)",
        "inverse-primary": "rgb(var(--c-inv-primary) / <alpha-value>)",
        "error": "rgb(var(--c-error) / <alpha-value>)",
        "error-container": "rgb(var(--c-error-ctr) / <alpha-value>)",
        "on-error": "rgb(var(--c-on-error) / <alpha-value>)",
        "on-error-container": "rgb(var(--c-on-error-ctr) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--c-on-primary-fx) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--c-on-primary-fx-v) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--c-on-secondary-fx) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--c-on-secondary-fx-v) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--c-on-tertiary-fx) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--c-on-tertiary-fx-v) / <alpha-value>)",
        "accent-tech": "rgb(var(--c-accent) / <alpha-value>)",
        "accent-tech-dim": "rgb(var(--c-accent-dim) / <alpha-value>)",
      },
      fontFamily: {
        "display": ["Space Grotesk", "sans-serif"],
        "heading": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display": ["clamp(1.875rem, 4.5vw + 0.5rem, 3.75rem)", { lineHeight: "1.12", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-sm": ["clamp(1.5rem, 3vw + 0.5rem, 2.75rem)", { lineHeight: "1.15", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-lg": ["clamp(1.4rem, 2.5vw + 0.5rem, 2.5rem)", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["clamp(1.15rem, 2vw + 0.5rem, 1.75rem)", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["clamp(1.05rem, 1.5vw + 0.5rem, 1.375rem)", { lineHeight: "1.35", letterSpacing: "-0.005em", fontWeight: "600" }],
        "title-lg": ["1.125rem", { lineHeight: "1.5", fontWeight: "600" }],
        "title-md": ["1.0625rem", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.7", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
        "body-xs": ["0.8125rem", { lineHeight: "1.5", fontWeight: "400" }],
        "label-lg": ["0.9375rem", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["0.8125rem", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["0.6875rem", { lineHeight: "1.3", letterSpacing: "0.04em", fontWeight: "600" }],
      },
      animation: {
        "fade-up": "fadeUp 0.6s ease-out forwards",
        "fade-in": "fadeIn 0.5s ease-out forwards",
      },
      keyframes: {
        fadeUp: { "0%": { opacity: "0", transform: "translateY(24px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
      },
    },
  },
};
